apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 188810905744.dkr.ecr.ap-northeast-2.amazonaws.com/dhkim-frontend
  newName: 188810905744.dkr.ecr.ap-northeast-2.amazonaws.com/dhkim-frontend
  newTag: a66d8a3a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
